name: Create Archive
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to be updated in all files'
        required: true
        default: '0.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Package
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'src/'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: 'v${{ github.event.inputs.version }}'
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
